[server]
; Allow access from LAN
http_addr = 0.0.0.0
http_port = 3000

[security]
; Allow embedding in your Flask App
allow_embedding = true

[auth.anonymous]
; Auto-login as Viewer
enabled = true
org_name = Main Org.
org_role = Viewer   