Autoconer_RH: 62.5
Autoconer_Temp: 29.2
Autoconer_iVa_Act_RH: 62.5
Autoconer_iVa_Act_Temp: 29.2
DI_Spg1_iFl_DCF1_OFF: 0
DI_Spg1_iFl_DCF1_ON: 1
DI_Spg1_iFl_DCF2_OFF: 0
DI_Spg1_iFl_DCF2_ON: 1
DI_Spg1_iFl_RDF1_OFF: 0
DI_Spg1_iFl_RDF1_ON: 0
DI_Spg1_iFl_RDF2_ON: 0
DI_Spg1_iFl_RetAFan1_OFF: 0
DI_Spg1_iFl_RetAFan1_ON: 1
DI_Spg1_iFl_RetAFan1_TRIP: 0
DI_Spg1_iFl_RetAFan2_OFF: 0
DI_Spg1_iFl_RetAFan2_ON: 1
DI_Spg1_iFl_RetAFan2_TRIP: 0
DI_Spg1_iFl_SAFan1_OFF: 0
DI_Spg1_iFl_SAFan1_ON: 1
DI_Spg1_iFl_SAFan1_TRIP: 0
DI_Spg1_iFl_SAFan2_OFF: 0
DI_Spg1_iFl_SAFan2_ON: 1
DI_Spg1_iFl_SAFan2_TRIP: 0
DI_Spg1_iFl_ScrewCompactor1_OFF: 0
DI_Spg1_iFl_ScrewCompactor1_ON: 1
DI_Spg1_iFl_ScrewCompactor2_OFF: 0
DI_Spg1_iFl_ScrewCompactor2_ON: 1
DI_Spg1_iFl_WasherPump1_OFF: 0
DI_Spg1_iFl_WasherPump1_ON: 1
DI_Spg1_iFl_WasherPump1_TRIP: 0
Spg1_DO_Pump_Act: 0
Spg1_DO_Pump_Act2: 0
Spg1_Damper_Pid_Para_Gain: 1.2
Spg1_Damper_Pid_Para_IntegrationTime: 100.0
Spg1_Humidity_Pid_Para_Gain: 3.0
Spg1_Humidity_Pid_Para_IntegrationTime: 400.0
Spg1_Temp_Pid_Para_Gain: 10.0
Spg1_Temp_Pid_Para_IntegrationTime: 1.0
Spg1_UPSS_Pid_Para_Gain: 1.2
Spg1_UPSS_Pid_Para_IntegrationTime: 350.0
Spg1_iFl_Damper_Output_Man_B: 1
Spg1_iFl_Humid_Output_Man_B: 0
Spg1_iFl_Humid_Output_Man_B2: 0
Spg1_iFl_Set_DPG_RDF_Man_B: 1
Spg1_iFl_Start_DO_B: 0
Spg1_iFl_Start_DO_B2: 0
Spg1_iMi_DO_Man: 0
Spg1_iMi_DO_Man2: 0
Spg1_iMi_Set_DPG_Man_REF: 0.0
Spg1_iMi_Set_RH: 55.0
Spg1_iMi_Set_RH_Man_Ref: 0.0
Spg1_iMi_Set_Temp: 36.0
Spg1_iMi_Set_Temp_Man_B: 1
Spg1_iMi_Set_Temp_Man_Ref: 0.0
Spg1_iMi_Set_WoT_Man_B: 1
Spg1_iMi_Set_WoT_Man_Ref: 0.0
Spg1_iTime_Start_Pump: 15
Spg1_iTime_Stop_Pump: 5
Spg1_iVa_Act_RH: 65.6
Spg1_iVa_Act_Temp: 38.2
Spg1_iVa_Act_WoT: 35.1
Spg1_iVa_DPG_RDF: -625.8
Spg1_iVa_Damper_Output: 95.0
Spg1_iVa_Damper_Output_Man_Ref: 100.0
Spg1_iVa_Damper_Pid_Output: 100.0
Spg1_iVa_Humid_Output_Man_Ref: 0.0
Spg1_iVa_Humid_Output_Man_Ref2: 0.0
Spg1_iVa_Humid_Pid_Out: 12.9
Spg1_iVa_Max_Damper_Output: 95.0
Spg1_iVa_Max_Humid_Output1: 96.0
Spg1_iVa_Max_RAF_UPSS: 96.0
Spg1_iVa_Max_SAF_UPSS: 78.0
Spg1_iVa_Min_Damper_Output: 5.0
Spg1_iVa_Min_Humd_Output1: 0.0
Spg1_iVa_Min_Pump_Output: 80.0
Spg1_iVa_Min_RAF_UPSS: 90.0
Spg1_iVa_Min_SAF_UPSS: 70.0
Spg1_iVa_Pid_Output_UPSS: 70.0
Spg1_iVa_Pump_Start_REF: 10.0
Spg1_iVa_Pump_Stop_REF: 5.0
Spg1_iVa_Ret_Damper_Output: 5.0
Spg1_iVa_Set_Temp_WoT: 26.6
Spg1_iVa_Temp_Pid_Output: 1.0
Spg1_iVa_UPSS_Output_RAF: 90.0
Spg1_iVa_UPSS_Output_SAF: 70.0
Spg1_iVa_WTC_Output: 12.9
Spg1_iVa_WTC_Output2: 13.0
Spinning 1_RH: 65.6
Spinning 1_Temp: 38.2
