DI_Prep_iFl_DCF_OFF: 1
DI_Prep_iFl_DCF_ON: 0
DI_Prep_iFl_DCF_TRIP: 0
DI_Prep_iFl_RDF_OFF: 1
DI_Prep_iFl_RDF_ON: 0
DI_Prep_iFl_RDF_TRIP: 0
DI_Prep_iFl_RetAFan_OFF: 1
DI_Prep_iFl_RetAFan_ON: 0
DI_Prep_iFl_RetAFan_TRIP: 0
DI_Prep_iFl_SAFan_OFF: 1
DI_Prep_iFl_SAFan_ON: 0
DI_Prep_iFl_SAFan_TRIP: 0
DI_Prep_iFl_ScrewCompactor_OFF: 1
DI_Prep_iFl_ScrewCompactor_ON: 0
DI_Prep_iFl_ScrewCompactor_TRIP: 0
DI_Prep_iFl_WasherPump_OFF: 1
DI_Prep_iFl_WasherPump_ON: 0
DI_Prep_iFl_WasherPump_TRIP: 0
DI_WCS_Card_iFl_Compactor_OFF: 1
DI_WCS_Card_iFl_Compactor_ON: 0
DI_WCS_Card_iFl_Compactor_Trip: 0
DI_WCS_Card_iFl_Conveyance_Fan_OFF: 1
DI_WCS_Card_iFl_Conveyance_Fan_ON: 0
DI_WCS_Card_iFl_Conveyance_Fan_Trip: 0
DI_WCS_Card_iFl_Cyclone_OFF: 1
DI_WCS_Card_iFl_Cyclone_ON: 0
DI_WCS_Card_iFl_Cyclone_Trip: 0
DI_WCS_Card_iFl_MainAirFan_OFF: 1
DI_WCS_Card_iFl_MainAirFan_ON: 0
DI_WCS_Card_iFl_MainAirFan_Trip: 0
DI_WCS_Card_iFl_PDF_OFF: 1
DI_WCS_Card_iFl_PDF_ON: 0
DI_WCS_Card_iFl_PDF_Trip: 0
DI_WCS_Card_iFl_RDF_OFF: 1
DI_WCS_Card_iFl_RDF_ON: 0
DI_WCS_Card_iFl_RDF_Trip: 0
DI_WCS_Card_iFl_TR_Fan_OFF: 1
DI_WCS_Card_iFl_TR_Fan_ON: 0
DI_WCS_Card_iFl_TR_Fan_Trip: 0
DI_WCS_Comber_iFl_Compactor_OFF: 1
DI_WCS_Comber_iFl_Compactor_ON: 0
DI_WCS_Comber_iFl_Compactor_Trip: 0
DI_WCS_Comber_iFl_MainAirFan_OFF: 1
DI_WCS_Comber_iFl_MainAirFan_ON: 0
DI_WCS_Comber_iFl_MainAirFan_Trip: 0
DI_WCS_Comber_iFl_PDF_OFF: 1
DI_WCS_Comber_iFl_PDF_ON: 0
DI_WCS_Comber_iFl_PDF_Trip: 0
DI_WCS_Comber_iFl_TR_Fan_OFF: 1
DI_WCS_Comber_iFl_TR_Fan_ON: 0
DI_WCS_Comber_iFl_TR_Fan_Trip: 0
OutSide_RH: 0.0
OutSide_Temp: -20.0
OutSide_iFl_RH_No_Signal_Alarm: 1
OutSide_iFl_RH_Sensor_Loss_Alarm: 0
OutSide_iFl_Temp_No_Signal_Alarm: 1
OutSide_iFl_Temp_Sensor_Loss_Alarm: 0
Prep_DO_Pump_Act: 1
Prep_Damper_Pid_Para_Gain: 2.0
Prep_Damper_Pid_Para_IntegrationTime: 240.0
Prep_DeHumidity_Gain: 1.5
Prep_DeHumidity_IntegrationTime: 240.0
Prep_Humidity_Pid_Para_Gain: 3.0
Prep_Humidity_Pid_Para_IntegrationTime: 300.0
Prep_Temp_Pid_Para_Gain: 6.0
Prep_Temp_Pid_Para_IntegrationTime: 1.0
Prep_UPSS_Pid_Para_Gain: 2.0
Prep_UPSS_Pid_Para_IntegrationTime: 240.0
Prep_iFl_DPT_High_Alarm: 0
Prep_iFl_DPT_Low_Alarm: 1
Prep_iFl_Damper_Output_Man_B: 0
Prep_iFl_Pump_Output_Man_B: 0
Prep_iFl_RH_High_Alarm: 0
Prep_iFl_RH_Low_Alarm: 1
Prep_iFl_SA_Temp_High_Alarm: 0
Prep_iFl_SA_Temp_Low_Alarm: 1
Prep_iFl_Set_DPT_RDF_Man_B: 0
Prep_iFl_Set_RH_Man_B: 0
Prep_iFl_Set_SA_Temp_Man_B: 0
Prep_iFl_Set_Temp_Man_B: 0
Prep_iFl_Start_DO_B: 0
Prep_iFl_Temp_High_Alarm: 0
Prep_iFl_Temp_Low_Alarm: 1
Prep_iFl_Update_Pid_Controller: 0
Prep_iFl_Update_Pid_UPSS: 0
Prep_iMi_DO_Man: 0
Prep_iMi_Set_DPT_High_Limit: 2000.0
Prep_iMi_Set_DPT_Low_Limit: 100.0
Prep_iMi_Set_DPT_RDF_Man_Ref: 0.0
Prep_iMi_Set_RH: 55.0
Prep_iMi_Set_RH_High_Limit: 60.0
Prep_iMi_Set_RH_Low_Limit: 40.0
Prep_iMi_Set_RH_Man_Ref: 0.0
Prep_iMi_Set_SA_Temp_High_Limit: 42.0
Prep_iMi_Set_SA_Temp_Low_Limit: 24.0
Prep_iMi_Set_SA_Temp_Man_Ref: 0.0
Prep_iMi_Set_Temp: 33.0
Prep_iMi_Set_Temp_High_Limit: 40.0
Prep_iMi_Set_Temp_Low_Limit: 28.0
Prep_iMi_Set_Temp_Man_Ref: 0.0
Prep_iTime_DeHumidity: 10
Prep_iTime_Start_Pump: 10
Prep_iTime_Stop_Pump: 10
Prep_iVA_Dehumid_Pid_Out: 0.0
Prep_iVa_Act_RH: 0.0
Prep_iVa_Act_SA_Temp: 0.0
Prep_iVa_Act_Temp: -20.0
Prep_iVa_DPT_RDF: 0.0
Prep_iVa_Damper_Output: 0.0
Prep_iVa_Damper_Output2: 0.0
Prep_iVa_Damper_Output_Man_Ref: 0.0
Prep_iVa_Damper_Pid_Output: 0.0
Prep_iVa_Humid_Pid_Out: 100.0
Prep_iVa_Inc_RH_Ref: 3.0
Prep_iVa_Max_Damper_Output: 100.0
Prep_iVa_Max_Humid_Output: 100.0
Prep_iVa_Max_RAF_UPSS: 100.0
Prep_iVa_Max_RH_Ref: 58.0
Prep_iVa_Max_SAF_UPSS: 100.0
Prep_iVa_Min_Damper_Output: 0.0
Prep_iVa_Min_Humid_Output: 0.0
Prep_iVa_Min_Pump_Output: 70.0
Prep_iVa_Min_RAF_UPSS: 0.0
Prep_iVa_Min_SAF_UPSS: 80.0
Prep_iVa_Pid_Output_UPSS: 100.0
Prep_iVa_Pump_Output: 100.0
Prep_iVa_Pump_Output_Man_Ref: 0.0
Prep_iVa_Pump_Start_REF: 15.0
Prep_iVa_Pump_Stop_REF: 5.0
Prep_iVa_Ret_Damper_Output: 100.0
Prep_iVa_Set_SA_Temp: 47.8
Prep_iVa_Temp_Pid_Output: 25.0
Prep_iVa_UPSS_Output_RAF: 20.0
Prep_iVa_UPSS_Output_SAF: 100.0
Preparatory_RH: 0.0
Preparatory_Temp: -20.0
WCS_Card_FDP_Pid_Para.Gain: 1.2
WCS_Card_FDP_Pid_Para.IntegrationTime: 400.0
WCS_Card_iFl_DPT_PDF_No_Signal_Alarm: 1
WCS_Card_iFl_DPT_PDF_Sensor_Loss_Alarm: 1
WCS_Card_iFl_DPT_RDF_No_Signal_Alarm: 1
WCS_Card_iFl_DPT_RDF_Sensor_Loss_Alarm: 1
WCS_Card_iFl_RadialFan_Output_Man_B: 0
WCS_Card_iFl_Set_DPT_PDF_Man_B: 0
WCS_Card_iFl_Set_DPT_RDF_Man_B: 0
WCS_Card_iFl_Update_Pid_FDP: 0
WCS_Card_iMi_Radial_Fan_Output_Man_Ref: 0.0
WCS_Card_iMi_Set_DPT_PDF_High_Limit: 0.0
WCS_Card_iMi_Set_DPT_PDF_Low_Limit: 0.0
WCS_Card_iMi_Set_DPT_PDF_Man_REF: 0.0
WCS_Card_iMi_Set_DPT_RDF_High_Limit: 0.0
WCS_Card_iMi_Set_DPT_RDF_Low_Limit: 0.0
WCS_Card_iMi_Set_Pressure: -700.0
WCS_Card_iVa_DPT_PDF: -2500.0
WCS_Card_iVa_DPT_RDF: 0.0
WCS_Card_iVa_Max_Radial_Fan: 100.0
WCS_Card_iVa_Min_Radial_Fan: 0.0
WCS_Card_iVa_Pid_Out_FDP: 0.0
WCS_Card_iVa_Radial_Fan: 0.0
WCS_Comber_FDP_Pid_Para.Gain: 1.2
WCS_Comber_FDP_Pid_Para.IntegrationTime: 400.0
WCS_Comber_iFl_DPT_PDF_No_Signal_Alarm: 1
WCS_Comber_iFl_RadialFan_Output_Man_B: 0
WCS_Comber_iFl_Set_DPT_PDF_Man_B: 0
WCS_Comber_iFl_Update_Pid_FDP: 0
WCS_Comber_iMi_Radial_Fan_Output_Man_Ref: 0.0
WCS_Comber_iMi_Set_DPT_PDF_High_Limit: 0.0
WCS_Comber_iMi_Set_DPT_PDF_Low_Limit: 0.0
WCS_Comber_iMi_Set_DPT_PDF_Man_REF: 0.0
WCS_Comber_iMi_Set_Pressure: -700.0
WCS_Comber_iVa_DPT_PDF: -2500.0
WCS_Comber_iVa_Max_Radial_Fan: 100.0
WCS_Comber_iVa_Min_Radial_Fan: 0.0
WCS_Comber_iVa_Pid_Out_FDP: 0.0
WCS_Comber_iVa_Radial_Fan: 0.0
