# =================================================================================
# Create-HtmlFiles.ps1
#
# DESCRIPTION:
# This script generates multiple HTML files based on a single template.
# It reads 'H-Plant-1.html', replaces the node prefix (e.g., 'Spg1') with
# a new prefix, updates the department title, and saves the result as a new
# file according to the mapping defined in the $departments array.
#
# USAGE:
# 1. Save this script as 'Create-HtmlFiles.ps1'.
# 2. Place it in the same directory as your 'H-Plant-1.html' file.
# 3. Open PowerShell in that directory.
# 4. Run the script by typing: .\Create-HtmlFiles.ps1
#
# NOTE:
# If you get an error about script execution, run this command first:
# Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process
# =================================================================================

# --- Configuration ---

# The source template file. Must be in the same directory as the script.
$sourceFile = @(
    "H-Plant-1.html",
    "H-Plant-2.html",
    "H-Plant-3.html",
    "H-Plant-4.html",
    "H-Plant-5.html",
    "H-Plant-6.html",
    "H-Plant-7.html",
    "H-Plant-8.html",
    "H-Plant-9.html",
    "H-Plant-10.html",
    "H-Plant-11.html",
    "H-Plant-12.html",
    "H-Plant-13.html",
    "H-Plant-14.html",
    "H-Plant-15.html",
    "H-Plant-16.html",
    "H-Plant-17.html",
    "H-Plant-18.html",
    "H-Plant-19.html",
    "H-Plant-20.html",
    "WCS-1.html",
    "WCS-2.html",
    "WCS-3.html",
    "WCS-4.html",
    "WCS-5.html"
)

# The original node prefix found in the source file that needs to be replaced.
$originalPrefix =  @("Prep","Prep1","Prep2","Spg", "Spg1", "spg2", "spg3", "TFO", "Wdg", "OE", "Lconer", "Aconer", "BR", "Card", "Comber", "Wvg", "Wvg1", "Wvg2", "Warp", "WvgL", "WvgL1", "WvgL2", "WvgL3", "Pcnl")

# --- Data Mapping (Transcribed from your image) ---
# Each object represents one new HTML file to be created.
$departments = @(
    [pscustomobject]@{ DepartmentName = 'Preparatory'; ShortName = 'Prep'; TemplateName = 'H-Plant-1_Prep' },
    [pscustomobject]@{ DepartmentName = 'Preparatory1'; ShortName = 'Prep1'; TemplateName = 'H-Plant-1_Prep1' },
    [pscustomobject]@{ DepartmentName = 'Preparatory2'; ShortName = 'Prep2'; TemplateName = 'H-Plant-1_Prep2' },
    [pscustomobject]@{ DepartmentName = 'Spinning'; ShortName = 'Spg'; TemplateName = 'H-Plant-1_Spg' },
    [pscustomobject]@{ DepartmentName = 'Spinning1'; ShortName = 'Spg1'; TemplateName = 'H-Plant-1_Spg1' },
    [pscustomobject]@{ DepartmentName = 'Spinning2'; ShortName = 'Spg2'; TemplateName = 'H-Plant-1_Sp2' }, # Note: Following image's template name exactly
    [pscustomobject]@{ DepartmentName = 'Spinning3'; ShortName = 'Spg3'; TemplateName = 'H-Plant-1_Spg3' },
    [pscustomobject]@{ DepartmentName = 'Winding'; ShortName = 'Wdg'; TemplateName = 'H-Plant-1_Wdg' },
    [pscustomobject]@{ DepartmentName = 'Open End'; ShortName = 'OE'; TemplateName = 'H-Plant-1_OE' },
    [pscustomobject]@{ DepartmentName = 'TFO'; ShortName = 'TFO'; TemplateName = 'H-Plant-1_TFO' },
    [pscustomobject]@{ DepartmentName = 'LinkConer'; ShortName = 'Lconer'; TemplateName = 'H-Plant-1_Lconer' },
    [pscustomobject]@{ DepartmentName = 'AutoConer'; ShortName = 'Aconer'; TemplateName = 'H-Plant-1_Aconer' },
    [pscustomobject]@{ DepartmentName = 'Weaving'; ShortName = 'Wvg'; TemplateName = 'H-Plant-1_Wvg' },
    [pscustomobject]@{ DepartmentName = 'Weaving1'; ShortName = 'Wvg1'; TemplateName = 'H-Plant-1_Wvg1' },
    [pscustomobject]@{ DepartmentName = 'Weaving2'; ShortName = 'Wvg2'; TemplateName = 'H-Plant-1_Wvg2' },
    [pscustomobject]@{ DepartmentName = 'Warping'; ShortName = 'Warp'; TemplateName = 'H-Plant-1_Warp' },
    [pscustomobject]@{ DepartmentName = 'Preparatory'; ShortName = 'Prep'; TemplateName = 'H-Plant-2_Prep' },
    [pscustomobject]@{ DepartmentName = 'Preparatory1'; ShortName = 'Prep1'; TemplateName = 'H-Plant-2_Prep1' },
    [pscustomobject]@{ DepartmentName = 'Preparatory2'; ShortName = 'Prep2'; TemplateName = 'H-Plant-2_Prep2' },
    [pscustomobject]@{ DepartmentName = 'Spinning'; ShortName = 'Spg'; TemplateName = 'H-Plant-2_Spg' },
    [pscustomobject]@{ DepartmentName = 'Spinning1'; ShortName = 'Spg1'; TemplateName = 'H-Plant-2_Spg1' },
    [pscustomobject]@{ DepartmentName = 'Spinning2'; ShortName = 'Spg2'; TemplateName = 'H-Plant-2_Sp2' }, # Note: Following image's template name exactly
    [pscustomobject]@{ DepartmentName = 'Spinning3'; ShortName = 'Spg3'; TemplateName = 'H-Plant-2_Spg3' },
    [pscustomobject]@{ DepartmentName = 'Winding'; ShortName = 'Wdg'; TemplateName = 'H-Plant-2_Wdg' },
    [pscustomobject]@{ DepartmentName = 'Open End'; ShortName = 'OE'; TemplateName = 'H-Plant-2_OE' },
    [pscustomobject]@{ DepartmentName = 'TFO'; ShortName = 'TFO'; TemplateName = 'H-Plant-2_TFO' },
    [pscustomobject]@{ DepartmentName = 'LinkConer'; ShortName = 'Lconer'; TemplateName = 'H-Plant-2_Lconer' },
    [pscustomobject]@{ DepartmentName = 'AutoConer'; ShortName = 'Aconer'; TemplateName = 'H-Plant-2_Aconer' },
    [pscustomobject]@{ DepartmentName = 'Weaving'; ShortName = 'Wvg'; TemplateName = 'H-Plant-2_Wvg' },
    [pscustomobject]@{ DepartmentName = 'Weaving1'; ShortName = 'Wvg1'; TemplateName = 'H-Plant-2_Wvg1' },
    [pscustomobject]@{ DepartmentName = 'Weaving2'; ShortName = 'Wvg2'; TemplateName = 'H-Plant-2_Wvg2' },
    [pscustomobject]@{ DepartmentName = 'Warping'; ShortName = 'Warp'; TemplateName = 'H-Plant-2_Warp' },
    [pscustomobject]@{ DepartmentName = 'Preparatory'; ShortName = 'Prep'; TemplateName = 'H-Plant-3_Prep' },
    [pscustomobject]@{ DepartmentName = 'Preparatory1'; ShortName = 'Prep1'; TemplateName = 'H-Plant-3_Prep1' },
    [pscustomobject]@{ DepartmentName = 'Preparatory2'; ShortName = 'Prep2'; TemplateName = 'H-Plant-3_Prep2' },
    [pscustomobject]@{ DepartmentName = 'Spinning'; ShortName = 'Spg'; TemplateName = 'H-Plant-3_Spg' },
    [pscustomobject]@{ DepartmentName = 'Spinning1'; ShortName = 'Spg1'; TemplateName = 'H-Plant-3_Spg1' },
    [pscustomobject]@{ DepartmentName = 'Spinning2'; ShortName = 'Spg2'; TemplateName = 'H-Plant-3_Sp2' }, # Note: Following image's template name exactly
    [pscustomobject]@{ DepartmentName = 'Spinning3'; ShortName = 'Spg3'; TemplateName = 'H-Plant-3_Spg3' },
    [pscustomobject]@{ DepartmentName = 'Winding'; ShortName = 'Wdg'; TemplateName = 'H-Plant-3_Wdg' },
    [pscustomobject]@{ DepartmentName = 'Open End'; ShortName = 'OE'; TemplateName = 'H-Plant-3_OE' },
    [pscustomobject]@{ DepartmentName = 'TFO'; ShortName = 'TFO'; TemplateName = 'H-Plant-3_TFO' },
    [pscustomobject]@{ DepartmentName = 'LinkConer'; ShortName = 'Lconer'; TemplateName = 'H-Plant-3_Lconer' },
    [pscustomobject]@{ DepartmentName = 'AutoConer'; ShortName = 'Aconer'; TemplateName = 'H-Plant-3_Aconer' },
    [pscustomobject]@{ DepartmentName = 'Weaving'; ShortName = 'Wvg'; TemplateName = 'H-Plant-3_Wvg' },
    [pscustomobject]@{ DepartmentName = 'Weaving1'; ShortName = 'Wvg1'; TemplateName = 'H-Plant-3_Wvg1' },
    [pscustomobject]@{ DepartmentName = 'Weaving2'; ShortName = 'Wvg2'; TemplateName = 'H-Plant-3_Wvg2' },
    [pscustomobject]@{ DepartmentName = 'Warping'; ShortName = 'Warp'; TemplateName = 'H-Plant-3_Warp' },
    [pscustomobject]@{ DepartmentName = 'Preparatory'; ShortName = 'Prep'; TemplateName = 'H-Plant-4_Prep' },
    [pscustomobject]@{ DepartmentName = 'Preparatory1'; ShortName = 'Prep1'; TemplateName = 'H-Plant-4_Prep1' },
    [pscustomobject]@{ DepartmentName = 'Preparatory2'; ShortName = 'Prep2'; TemplateName = 'H-Plant-4_Prep2' },
    [pscustomobject]@{ DepartmentName = 'Spinning'; ShortName = 'Spg'; TemplateName = 'H-Plant-4_Spg' },
    [pscustomobject]@{ DepartmentName = 'Spinning1'; ShortName = 'Spg1'; TemplateName = 'H-Plant-4_Spg1' },
    [pscustomobject]@{ DepartmentName = 'Spinning2'; ShortName = 'Spg2'; TemplateName = 'H-Plant-4_Sp2' }, # Note: Following image's template name exactly
    [pscustomobject]@{ DepartmentName = 'Spinning3'; ShortName = 'Spg3'; TemplateName = 'H-Plant-4_Spg3' },
    [pscustomobject]@{ DepartmentName = 'Winding'; ShortName = 'Wdg'; TemplateName = 'H-Plant-4_Wdg' },
    [pscustomobject]@{ DepartmentName = 'Open End'; ShortName = 'OE'; TemplateName = 'H-Plant-4_OE' },
    [pscustomobject]@{ DepartmentName = 'TFO'; ShortName = 'TFO'; TemplateName = 'H-Plant-4_TFO' },
    [pscustomobject]@{ DepartmentName = 'LinkConer'; ShortName = 'Lconer'; TemplateName = 'H-Plant-4_Lconer' },
    [pscustomobject]@{ DepartmentName = 'AutoConer'; ShortName = 'Aconer'; TemplateName = 'H-Plant-4_Aconer' },
    [pscustomobject]@{ DepartmentName = 'Weaving'; ShortName = 'Wvg'; TemplateName = 'H-Plant-4_Wvg' },
    [pscustomobject]@{ DepartmentName = 'Weaving1'; ShortName = 'Wvg1'; TemplateName = 'H-Plant-4_Wvg1' },
    [pscustomobject]@{ DepartmentName = 'Weaving2'; ShortName = 'Wvg2'; TemplateName = 'H-Plant-4_Wvg2' },
    [pscustomobject]@{ DepartmentName = 'Warping'; ShortName = 'Warp'; TemplateName = 'H-Plant-4_Warp' },
    [pscustomobject]@{ DepartmentName = 'Preparatory'; ShortName = 'Prep'; TemplateName = 'H-Plant-5_Prep' },
    [pscustomobject]@{ DepartmentName = 'Preparatory1'; ShortName = 'Prep1'; TemplateName = 'H-Plant-5_Prep1' },
    [pscustomobject]@{ DepartmentName = 'Preparatory2'; ShortName = 'Prep2'; TemplateName = 'H-Plant-5_Prep2' },
    [pscustomobject]@{ DepartmentName = 'Spinning'; ShortName = 'Spg'; TemplateName = 'H-Plant-5_Spg' },
    [pscustomobject]@{ DepartmentName = 'Spinning1'; ShortName = 'Spg1'; TemplateName = 'H-Plant-5_Spg1' },
    [pscustomobject]@{ DepartmentName = 'Spinning2'; ShortName = 'Spg2'; TemplateName = 'H-Plant-5_Sp2' }, # Note: Following image's template name exactly
    [pscustomobject]@{ DepartmentName = 'Spinning3'; ShortName = 'Spg3'; TemplateName = 'H-Plant-5_Spg3' },
    [pscustomobject]@{ DepartmentName = 'Winding'; ShortName = 'Wdg'; TemplateName = 'H-Plant-5_Wdg' },
    [pscustomobject]@{ DepartmentName = 'Open End'; ShortName = 'OE'; TemplateName = 'H-Plant-5_OE' },
    [pscustomobject]@{ DepartmentName = 'TFO'; ShortName = 'TFO'; TemplateName = 'H-Plant-5_TFO' },
    [pscustomobject]@{ DepartmentName = 'LinkConer'; ShortName = 'Lconer'; TemplateName = 'H-Plant-5_Lconer' },
    [pscustomobject]@{ DepartmentName = 'AutoConer'; ShortName = 'Aconer'; TemplateName = 'H-Plant-5_Aconer' },
    [pscustomobject]@{ DepartmentName = 'Weaving'; ShortName = 'Wvg'; TemplateName = 'H-Plant-5_Wvg' },
    [pscustomobject]@{ DepartmentName = 'Weaving1'; ShortName = 'Wvg1'; TemplateName = 'H-Plant-5_Wvg1' },
    [pscustomobject]@{ DepartmentName = 'Weaving2'; ShortName = 'Wvg2'; TemplateName = 'H-Plant-5_Wvg2' },
    [pscustomobject]@{ DepartmentName = 'Warping'; ShortName = 'Warp'; TemplateName = 'H-Plant-5_Warp' },
    [pscustomobject]@{ DepartmentName = 'Preparatory'; ShortName = 'Prep'; TemplateName = 'H-Plant-6_Prep' },
    [pscustomobject]@{ DepartmentName = 'Preparatory1'; ShortName = 'Prep1'; TemplateName = 'H-Plant-6_Prep1' },
    [pscustomobject]@{ DepartmentName = 'Preparatory2'; ShortName = 'Prep2'; TemplateName = 'H-Plant-6_Prep2' },
    [pscustomobject]@{ DepartmentName = 'Spinning'; ShortName = 'Spg'; TemplateName = 'H-Plant-6_Spg' },
    [pscustomobject]@{ DepartmentName = 'Spinning1'; ShortName = 'Spg1'; TemplateName = 'H-Plant-6_Spg1' },
    [pscustomobject]@{ DepartmentName = 'Spinning2'; ShortName = 'Spg2'; TemplateName = 'H-Plant-6_Sp2' }, # Note: Following image's template name exactly
    [pscustomobject]@{ DepartmentName = 'Spinning3'; ShortName = 'Spg3'; TemplateName = 'H-Plant-6_Spg3' },
    [pscustomobject]@{ DepartmentName = 'Winding'; ShortName = 'Wdg'; TemplateName = 'H-Plant-6_Wdg' },
    [pscustomobject]@{ DepartmentName = 'Open End'; ShortName = 'OE'; TemplateName = 'H-Plant-6_OE' },
    [pscustomobject]@{ DepartmentName = 'TFO'; ShortName = 'TFO'; TemplateName = 'H-Plant-6_TFO' },
    [pscustomobject]@{ DepartmentName = 'LinkConer'; ShortName = 'Lconer'; TemplateName = 'H-Plant-6_Lconer' },
    [pscustomobject]@{ DepartmentName = 'AutoConer'; ShortName = 'Aconer'; TemplateName = 'H-Plant-6_Aconer' },
    [pscustomobject]@{ DepartmentName = 'Weaving'; ShortName = 'Wvg'; TemplateName = 'H-Plant-6_Wvg' },
    [pscustomobject]@{ DepartmentName = 'Weaving1'; ShortName = 'Wvg1'; TemplateName = 'H-Plant-6_Wvg1' },
    [pscustomobject]@{ DepartmentName = 'Weaving2'; ShortName = 'Wvg2'; TemplateName = 'H-Plant-6_Wvg2' },
    [pscustomobject]@{ DepartmentName = 'Warping'; ShortName = 'Warp'; TemplateName = 'H-Plant-6_Warp' },
    [pscustomobject]@{ DepartmentName = 'Preparatory'; ShortName = 'Prep'; TemplateName = 'H-Plant-7_Prep' },
    [pscustomobject]@{ DepartmentName = 'Preparatory1'; ShortName = 'Prep1'; TemplateName = 'H-Plant-7_Prep1' },
    [pscustomobject]@{ DepartmentName = 'Preparatory2'; ShortName = 'Prep2'; TemplateName = 'H-Plant-7_Prep2' },
    [pscustomobject]@{ DepartmentName = 'Spinning'; ShortName = 'Spg'; TemplateName = 'H-Plant-7_Spg' },
    [pscustomobject]@{ DepartmentName = 'Spinning1'; ShortName = 'Spg1'; TemplateName = 'H-Plant-7_Spg1' },
    [pscustomobject]@{ DepartmentName = 'Spinning2'; ShortName = 'Spg2'; TemplateName = 'H-Plant-7_Sp2' }, # Note: Following image's template name exactly
    [pscustomobject]@{ DepartmentName = 'Spinning3'; ShortName = 'Spg3'; TemplateName = 'H-Plant-7_Spg3' },
    [pscustomobject]@{ DepartmentName = 'Winding'; ShortName = 'Wdg'; TemplateName = 'H-Plant-7_Wdg' },
    [pscustomobject]@{ DepartmentName = 'Open End'; ShortName = 'OE'; TemplateName = 'H-Plant-7_OE' },
    [pscustomobject]@{ DepartmentName = 'TFO'; ShortName = 'TFO'; TemplateName = 'H-Plant-7_TFO' },
    [pscustomobject]@{ DepartmentName = 'LinkConer'; ShortName = 'Lconer'; TemplateName = 'H-Plant-7_Lconer' },
    [pscustomobject]@{ DepartmentName = 'AutoConer'; ShortName = 'Aconer'; TemplateName = 'H-Plant-7_Aconer' },
    [pscustomobject]@{ DepartmentName = 'Weaving'; ShortName = 'Wvg'; TemplateName = 'H-Plant-7_Wvg' },
    [pscustomobject]@{ DepartmentName = 'Weaving1'; ShortName = 'Wvg1'; TemplateName = 'H-Plant-7_Wvg1' },
    [pscustomobject]@{ DepartmentName = 'Weaving2'; ShortName = 'Wvg2'; TemplateName = 'H-Plant-7_Wvg2' },
    [pscustomobject]@{ DepartmentName = 'Warping'; ShortName = 'Warp'; TemplateName = 'H-Plant-7_Warp' },
    [pscustomobject]@{ DepartmentName = 'Preparatory'; ShortName = 'Prep'; TemplateName = 'H-Plant-8_Prep' },
    [pscustomobject]@{ DepartmentName = 'Preparatory1'; ShortName = 'Prep1'; TemplateName = 'H-Plant-8_Prep1' },
    [pscustomobject]@{ DepartmentName = 'Preparatory2'; ShortName = 'Prep2'; TemplateName = 'H-Plant-8_Prep2' },
    [pscustomobject]@{ DepartmentName = 'Spinning'; ShortName = 'Spg'; TemplateName = 'H-Plant-8_Spg' },
    [pscustomobject]@{ DepartmentName = 'Spinning1'; ShortName = 'Spg1'; TemplateName = 'H-Plant-8_Spg1' },
    [pscustomobject]@{ DepartmentName = 'Spinning2'; ShortName = 'Spg2'; TemplateName = 'H-Plant-8_Sp2' }, # Note: Following image's template name exactly
    [pscustomobject]@{ DepartmentName = 'Spinning3'; ShortName = 'Spg3'; TemplateName = 'H-Plant-8_Spg3' },
    [pscustomobject]@{ DepartmentName = 'Winding'; ShortName = 'Wdg'; TemplateName = 'H-Plant-8_Wdg' },
    [pscustomobject]@{ DepartmentName = 'Open End'; ShortName = 'OE'; TemplateName = 'H-Plant-8_OE' },
    [pscustomobject]@{ DepartmentName = 'TFO'; ShortName = 'TFO'; TemplateName = 'H-Plant-8_TFO' },
    [pscustomobject]@{ DepartmentName = 'LinkConer'; ShortName = 'Lconer'; TemplateName = 'H-Plant-8_Lconer' },
    [pscustomobject]@{ DepartmentName = 'AutoConer'; ShortName = 'Aconer'; TemplateName = 'H-Plant-8_Aconer' },
    [pscustomobject]@{ DepartmentName = 'Weaving'; ShortName = 'Wvg'; TemplateName = 'H-Plant-8_Wvg' },
    [pscustomobject]@{ DepartmentName = 'Weaving1'; ShortName = 'Wvg1'; TemplateName = 'H-Plant-8_Wvg1' },
    [pscustomobject]@{ DepartmentName = 'Weaving2'; ShortName = 'Wvg2'; TemplateName = 'H-Plant-8_Wvg2' },
    [pscustomobject]@{ DepartmentName = 'Warping'; ShortName = 'Warp'; TemplateName = 'H-Plant-8_Warp' },
    [pscustomobject]@{ DepartmentName = 'Preparatory'; ShortName = 'Prep'; TemplateName = 'H-Plant-9_Prep' },
    [pscustomobject]@{ DepartmentName = 'Preparatory1'; ShortName = 'Prep1'; TemplateName = 'H-Plant-9_Prep1' },
    [pscustomobject]@{ DepartmentName = 'Preparatory2'; ShortName = 'Prep2'; TemplateName = 'H-Plant-9_Prep2' },
    [pscustomobject]@{ DepartmentName = 'Spinning'; ShortName = 'Spg'; TemplateName = 'H-Plant-9_Spg' },
    [pscustomobject]@{ DepartmentName = 'Spinning1'; ShortName = 'Spg1'; TemplateName = 'H-Plant-9_Spg1' },
    [pscustomobject]@{ DepartmentName = 'Spinning2'; ShortName = 'Spg2'; TemplateName = 'H-Plant-9_Sp2' }, # Note: Following image's template name exactly
    [pscustomobject]@{ DepartmentName = 'Spinning3'; ShortName = 'Spg3'; TemplateName = 'H-Plant-9_Spg3' },
    [pscustomobject]@{ DepartmentName = 'Winding'; ShortName = 'Wdg'; TemplateName = 'H-Plant-9_Wdg' },
    [pscustomobject]@{ DepartmentName = 'Open End'; ShortName = 'OE'; TemplateName = 'H-Plant-9_OE' },
    [pscustomobject]@{ DepartmentName = 'TFO'; ShortName = 'TFO'; TemplateName = 'H-Plant-9_TFO' },
    [pscustomobject]@{ DepartmentName = 'LinkConer'; ShortName = 'Lconer'; TemplateName = 'H-Plant-9_Lconer' },
    [pscustomobject]@{ DepartmentName = 'AutoConer'; ShortName = 'Aconer'; TemplateName = 'H-Plant-9_Aconer' },
    [pscustomobject]@{ DepartmentName = 'Weaving'; ShortName = 'Wvg'; TemplateName = 'H-Plant-9_Wvg' },
    [pscustomobject]@{ DepartmentName = 'Weaving1'; ShortName = 'Wvg1'; TemplateName = 'H-Plant-9_Wvg1' },
    [pscustomobject]@{ DepartmentName = 'Weaving2'; ShortName = 'Wvg2'; TemplateName = 'H-Plant-9_Wvg2' },
    [pscustomobject]@{ DepartmentName = 'Warping'; ShortName = 'Warp'; TemplateName = 'H-Plant-9_Warp' },
    [pscustomobject]@{ DepartmentName = 'Preparatory'; ShortName = 'Prep'; TemplateName = 'H-Plant-10_Prep' },
    [pscustomobject]@{ DepartmentName = 'Preparatory1'; ShortName = 'Prep1'; TemplateName = 'H-Plant-10_Prep1' },
    [pscustomobject]@{ DepartmentName = 'Preparatory2'; ShortName = 'Prep2'; TemplateName = 'H-Plant-10_Prep2' },
    [pscustomobject]@{ DepartmentName = 'Spinning'; ShortName = 'Spg'; TemplateName = 'H-Plant-10_Spg' },
    [pscustomobject]@{ DepartmentName = 'Spinning1'; ShortName = 'Spg1'; TemplateName = 'H-Plant-10_Spg1' },
    [pscustomobject]@{ DepartmentName = 'Spinning2'; ShortName = 'Spg2'; TemplateName = 'H-Plant-10_Sp2' }, # Note: Following image's template name exactly
    [pscustomobject]@{ DepartmentName = 'Spinning3'; ShortName = 'Spg3'; TemplateName = 'H-Plant-10_Spg3' },
    [pscustomobject]@{ DepartmentName = 'Winding'; ShortName = 'Wdg'; TemplateName = 'H-Plant-10_Wdg' },
    [pscustomobject]@{ DepartmentName = 'Open End'; ShortName = 'OE'; TemplateName = 'H-Plant-10_OE' },
    [pscustomobject]@{ DepartmentName = 'TFO'; ShortName = 'TFO'; TemplateName = 'H-Plant-10_TFO' },
    [pscustomobject]@{ DepartmentName = 'LinkConer'; ShortName = 'Lconer'; TemplateName = 'H-Plant-10_Lconer' },
    [pscustomobject]@{ DepartmentName = 'AutoConer'; ShortName = 'Aconer'; TemplateName = 'H-Plant-10_Aconer' },
    [pscustomobject]@{ DepartmentName = 'Weaving'; ShortName = 'Wvg'; TemplateName = 'H-Plant-10_Wvg' },
    [pscustomobject]@{ DepartmentName = 'Weaving1'; ShortName = 'Wvg1'; TemplateName = 'H-Plant-10_Wvg1' },
    [pscustomobject]@{ DepartmentName = 'Weaving2'; ShortName = 'Wvg2'; TemplateName = 'H-Plant-10_Wvg2' },
    [pscustomobject]@{ DepartmentName = 'Warping'; ShortName = 'Warp'; TemplateName = 'H-Plant-10_Warp' },
    [pscustomobject]@{ DepartmentName = 'BlowRoom'; ShortName = 'BR'; TemplateName = 'H-Plant-10_BR' },
    [pscustomobject]@{ DepartmentName = 'Preparatory'; ShortName = 'Prep'; TemplateName = 'H-Plant-11_Prep' },
    [pscustomobject]@{ DepartmentName = 'Preparatory1'; ShortName = 'Prep1'; TemplateName = 'H-Plant-11_Prep1' },
    [pscustomobject]@{ DepartmentName = 'Preparatory2'; ShortName = 'Prep2'; TemplateName = 'H-Plant-11_Prep2' },
    [pscustomobject]@{ DepartmentName = 'Spinning'; ShortName = 'Spg'; TemplateName = 'H-Plant-11_Spg' },
    [pscustomobject]@{ DepartmentName = 'Spinning1'; ShortName = 'Spg1'; TemplateName = 'H-Plant-11_Spg1' },
    [pscustomobject]@{ DepartmentName = 'Spinning2'; ShortName = 'Spg2'; TemplateName = 'H-Plant-11_Sp2' }, # Note: Following image's template name exactly
    [pscustomobject]@{ DepartmentName = 'Spinning3'; ShortName = 'Spg3'; TemplateName = 'H-Plant-11_Spg3' },
    [pscustomobject]@{ DepartmentName = 'Winding'; ShortName = 'Wdg'; TemplateName = 'H-Plant-11_Wdg' },
    [pscustomobject]@{ DepartmentName = 'Open End'; ShortName = 'OE'; TemplateName = 'H-Plant-11_OE' },
    [pscustomobject]@{ DepartmentName = 'TFO'; ShortName = 'TFO'; TemplateName = 'H-Plant-11_TFO' },
    [pscustomobject]@{ DepartmentName = 'LinkConer'; ShortName = 'Lconer'; TemplateName = 'H-Plant-11_Lconer' },
    [pscustomobject]@{ DepartmentName = 'AutoConer'; ShortName = 'Aconer'; TemplateName = 'H-Plant-11_Aconer' },
    [pscustomobject]@{ DepartmentName = 'Weaving'; ShortName = 'Wvg'; TemplateName = 'H-Plant-11_Wvg' },
    [pscustomobject]@{ DepartmentName = 'Weaving1'; ShortName = 'Wvg1'; TemplateName = 'H-Plant-11_Wvg1' },
    [pscustomobject]@{ DepartmentName = 'Weaving2'; ShortName = 'Wvg2'; TemplateName = 'H-Plant-11_Wvg2' },
    [pscustomobject]@{ DepartmentName = 'Warping'; ShortName = 'Warp'; TemplateName = 'H-Plant-11_Warp' },
    [pscustomobject]@{ DepartmentName = 'BlowRoom'; ShortName = 'BR'; TemplateName = 'H-Plant-11_BR' },
    [pscustomobject]@{ DepartmentName = 'Preparatory'; ShortName = 'Prep'; TemplateName = 'H-Plant-12_Prep' },
    [pscustomobject]@{ DepartmentName = 'Preparatory1'; ShortName = 'Prep1'; TemplateName = 'H-Plant-12_Prep1' },
    [pscustomobject]@{ DepartmentName = 'Preparatory2'; ShortName = 'Prep2'; TemplateName = 'H-Plant-12_Prep2' },
    [pscustomobject]@{ DepartmentName = 'Spinning'; ShortName = 'Spg'; TemplateName = 'H-Plant-12_Spg' },
    [pscustomobject]@{ DepartmentName = 'Spinning1'; ShortName = 'Spg1'; TemplateName = 'H-Plant-12_Spg1' },
    [pscustomobject]@{ DepartmentName = 'Spinning2'; ShortName = 'Spg2'; TemplateName = 'H-Plant-12_Sp2' }, # Note: Following image's template name exactly
    [pscustomobject]@{ DepartmentName = 'Spinning3'; ShortName = 'Spg3'; TemplateName = 'H-Plant-12_Spg3' },
    [pscustomobject]@{ DepartmentName = 'Winding'; ShortName = 'Wdg'; TemplateName = 'H-Plant-12_Wdg' },
    [pscustomobject]@{ DepartmentName = 'Open End'; ShortName = 'OE'; TemplateName = 'H-Plant-12_OE' },
    [pscustomobject]@{ DepartmentName = 'TFO'; ShortName = 'TFO'; TemplateName = 'H-Plant-12_TFO' },
    [pscustomobject]@{ DepartmentName = 'LinkConer'; ShortName = 'Lconer'; TemplateName = 'H-Plant-12_Lconer' },
    [pscustomobject]@{ DepartmentName = 'AutoConer'; ShortName = 'Aconer'; TemplateName = 'H-Plant-12_Aconer' },
    [pscustomobject]@{ DepartmentName = 'Weaving'; ShortName = 'Wvg'; TemplateName = 'H-Plant-12_Wvg' },
    [pscustomobject]@{ DepartmentName = 'Weaving1'; ShortName = 'Wvg1'; TemplateName = 'H-Plant-12_Wvg1' },
    [pscustomobject]@{ DepartmentName = 'Weaving2'; ShortName = 'Wvg2'; TemplateName = 'H-Plant-12_Wvg2' },
    [pscustomobject]@{ DepartmentName = 'Warping'; ShortName = 'Warp'; TemplateName = 'H-Plant-12_Warp' },
    [pscustomobject]@{ DepartmentName = 'BlowRoom'; ShortName = 'BR'; TemplateName = 'H-Plant-12_BR' },
    [pscustomobject]@{ DepartmentName = 'Preparatory'; ShortName = 'Prep'; TemplateName = 'H-Plant-13_Prep' },
    [pscustomobject]@{ DepartmentName = 'Preparatory1'; ShortName = 'Prep1'; TemplateName = 'H-Plant-13_Prep1' },
    [pscustomobject]@{ DepartmentName = 'Preparatory2'; ShortName = 'Prep2'; TemplateName = 'H-Plant-13_Prep2' },
    [pscustomobject]@{ DepartmentName = 'Spinning'; ShortName = 'Spg'; TemplateName = 'H-Plant-13_Spg' },
    [pscustomobject]@{ DepartmentName = 'Spinning1'; ShortName = 'Spg1'; TemplateName = 'H-Plant-13_Spg1' },
    [pscustomobject]@{ DepartmentName = 'Spinning2'; ShortName = 'Spg2'; TemplateName = 'H-Plant-13_Sp2' }, # Note: Following image's template name exactly
    [pscustomobject]@{ DepartmentName = 'Spinning3'; ShortName = 'Spg3'; TemplateName = 'H-Plant-13_Spg3' },
    [pscustomobject]@{ DepartmentName = 'Winding'; ShortName = 'Wdg'; TemplateName = 'H-Plant-13_Wdg' },
    [pscustomobject]@{ DepartmentName = 'Open End'; ShortName = 'OE'; TemplateName = 'H-Plant-13_OE' },
    [pscustomobject]@{ DepartmentName = 'TFO'; ShortName = 'TFO'; TemplateName = 'H-Plant-13_TFO' },
    [pscustomobject]@{ DepartmentName = 'LinkConer'; ShortName = 'Lconer'; TemplateName = 'H-Plant-13_Lconer' },
    [pscustomobject]@{ DepartmentName = 'AutoConer'; ShortName = 'Aconer'; TemplateName = 'H-Plant-13_Aconer' },
    [pscustomobject]@{ DepartmentName = 'Weaving'; ShortName = 'Wvg'; TemplateName = 'H-Plant-13_Wvg' },
    [pscustomobject]@{ DepartmentName = 'Weaving1'; ShortName = 'Wvg1'; TemplateName = 'H-Plant-13_Wvg1' },
    [pscustomobject]@{ DepartmentName = 'Weaving2'; ShortName = 'Wvg2'; TemplateName = 'H-Plant-13_Wvg2' },
    [pscustomobject]@{ DepartmentName = 'Warping'; ShortName = 'Warp'; TemplateName = 'H-Plant-13_Warp' },
    [pscustomobject]@{ DepartmentName = 'BlowRoom'; ShortName = 'BR'; TemplateName = 'H-Plant-13_BR' },
    [pscustomobject]@{ DepartmentName = 'WeavingLoom'; ShortName = 'WvgL'; TemplateName = 'H-Plant-13_WvgL' },
    [pscustomobject]@{ DepartmentName = 'WeavingLoom1'; ShortName = 'WvgL1'; TemplateName = 'H-Plant-13_WvgL1' },
    [pscustomobject]@{ DepartmentName = 'WeavingLoom2'; ShortName = 'WvgL2'; TemplateName = 'H-Plant-13_WvgL2' },
    [pscustomobject]@{ DepartmentName = 'WeavingLoom3'; ShortName = 'WvgL3'; TemplateName = 'H-Plant-13_WvgL3' },
    [pscustomobject]@{ DepartmentName = 'Picanal'; ShortName = 'Pcnl'; TemplateName = 'H-Plant-13_Pcnl' },
    [pscustomobject]@{ DepartmentName = 'Preparatory'; ShortName = 'Prep'; TemplateName = 'H-Plant-14_Prep' },
    [pscustomobject]@{ DepartmentName = 'Preparatory1'; ShortName = 'Prep1'; TemplateName = 'H-Plant-14_Prep1' },
    [pscustomobject]@{ DepartmentName = 'Preparatory2'; ShortName = 'Prep2'; TemplateName = 'H-Plant-14_Prep2' },
    [pscustomobject]@{ DepartmentName = 'Spinning'; ShortName = 'Spg'; TemplateName = 'H-Plant-14_Spg' },
    [pscustomobject]@{ DepartmentName = 'Spinning1'; ShortName = 'Spg1'; TemplateName = 'H-Plant-14_Spg1' },
    [pscustomobject]@{ DepartmentName = 'Spinning2'; ShortName = 'Spg2'; TemplateName = 'H-Plant-14_Sp2' }, # Note: Following image's template name exactly
    [pscustomobject]@{ DepartmentName = 'Spinning3'; ShortName = 'Spg3'; TemplateName = 'H-Plant-14_Spg3' },
    [pscustomobject]@{ DepartmentName = 'Winding'; ShortName = 'Wdg'; TemplateName = 'H-Plant-14_Wdg' },
    [pscustomobject]@{ DepartmentName = 'Open End'; ShortName = 'OE'; TemplateName = 'H-Plant-14_OE' },
    [pscustomobject]@{ DepartmentName = 'TFO'; ShortName = 'TFO'; TemplateName = 'H-Plant-14_TFO' },
    [pscustomobject]@{ DepartmentName = 'LinkConer'; ShortName = 'Lconer'; TemplateName = 'H-Plant-14_Lconer' },
    [pscustomobject]@{ DepartmentName = 'AutoConer'; ShortName = 'Aconer'; TemplateName = 'H-Plant-14_Aconer' },
    [pscustomobject]@{ DepartmentName = 'Weaving'; ShortName = 'Wvg'; TemplateName = 'H-Plant-14_Wvg' },
    [pscustomobject]@{ DepartmentName = 'Weaving1'; ShortName = 'Wvg1'; TemplateName = 'H-Plant-14_Wvg1' },
    [pscustomobject]@{ DepartmentName = 'Weaving2'; ShortName = 'Wvg2'; TemplateName = 'H-Plant-14_Wvg2' },
    [pscustomobject]@{ DepartmentName = 'Warping'; ShortName = 'Warp'; TemplateName = 'H-Plant-14_Warp' },
    [pscustomobject]@{ DepartmentName = 'BlowRoom'; ShortName = 'BR'; TemplateName = 'H-Plant-14_BR' },
    [pscustomobject]@{ DepartmentName = 'WeavingLoom'; ShortName = 'WvgL'; TemplateName = 'H-Plant-14_WvgL' },
    [pscustomobject]@{ DepartmentName = 'WeavingLoom1'; ShortName = 'WvgL1'; TemplateName = 'H-Plant-14_WvgL1' },
    [pscustomobject]@{ DepartmentName = 'WeavingLoom2'; ShortName = 'WvgL2'; TemplateName = 'H-Plant-14_WvgL2' },
    [pscustomobject]@{ DepartmentName = 'WeavingLoom3'; ShortName = 'WvgL3'; TemplateName = 'H-Plant-14_WvgL3' },
    [pscustomobject]@{ DepartmentName = 'Picanal'; ShortName = 'Pcnl'; TemplateName = 'H-Plant-14_Pcnl' },
    [pscustomobject]@{ DepartmentName = 'Preparatory'; ShortName = 'Prep'; TemplateName = 'H-Plant-15_Prep' },
    [pscustomobject]@{ DepartmentName = 'Preparatory1'; ShortName = 'Prep1'; TemplateName = 'H-Plant-15_Prep1' },
    [pscustomobject]@{ DepartmentName = 'Preparatory2'; ShortName = 'Prep2'; TemplateName = 'H-Plant-15_Prep2' },
    [pscustomobject]@{ DepartmentName = 'Spinning'; ShortName = 'Spg'; TemplateName = 'H-Plant-15_Spg' },
    [pscustomobject]@{ DepartmentName = 'Spinning1'; ShortName = 'Spg1'; TemplateName = 'H-Plant-15_Spg1' },
    [pscustomobject]@{ DepartmentName = 'Spinning2'; ShortName = 'Spg2'; TemplateName = 'H-Plant-15_Sp2' }, # Note: Following image's template name exactly
    [pscustomobject]@{ DepartmentName = 'Spinning3'; ShortName = 'Spg3'; TemplateName = 'H-Plant-15_Spg3' },
    [pscustomobject]@{ DepartmentName = 'Winding'; ShortName = 'Wdg'; TemplateName = 'H-Plant-15_Wdg' },
    [pscustomobject]@{ DepartmentName = 'Open End'; ShortName = 'OE'; TemplateName = 'H-Plant-15_OE' },
    [pscustomobject]@{ DepartmentName = 'TFO'; ShortName = 'TFO'; TemplateName = 'H-Plant-15_TFO' },
    [pscustomobject]@{ DepartmentName = 'LinkConer'; ShortName = 'Lconer'; TemplateName = 'H-Plant-15_Lconer' },
    [pscustomobject]@{ DepartmentName = 'AutoConer'; ShortName = 'Aconer'; TemplateName = 'H-Plant-15_Aconer' },
    [pscustomobject]@{ DepartmentName = 'Weaving'; ShortName = 'Wvg'; TemplateName = 'H-Plant-15_Wvg' },
    [pscustomobject]@{ DepartmentName = 'Weaving1'; ShortName = 'Wvg1'; TemplateName = 'H-Plant-15_Wvg1' },
    [pscustomobject]@{ DepartmentName = 'Weaving2'; ShortName = 'Wvg2'; TemplateName = 'H-Plant-15_Wvg2' },
    [pscustomobject]@{ DepartmentName = 'Warping'; ShortName = 'Warp'; TemplateName = 'H-Plant-15_Warp' },
    [pscustomobject]@{ DepartmentName = 'BlowRoom'; ShortName = 'BR'; TemplateName = 'H-Plant-15_BR' },
    [pscustomobject]@{ DepartmentName = 'WeavingLoom'; ShortName = 'WvgL'; TemplateName = 'H-Plant-15_WvgL' },
    [pscustomobject]@{ DepartmentName = 'WeavingLoom1'; ShortName = 'WvgL1'; TemplateName = 'H-Plant-15_WvgL1' },
    [pscustomobject]@{ DepartmentName = 'WeavingLoom2'; ShortName = 'WvgL2'; TemplateName = 'H-Plant-15_WvgL2' },
    [pscustomobject]@{ DepartmentName = 'WeavingLoom3'; ShortName = 'WvgL3'; TemplateName = 'H-Plant-15_WvgL3' },
    [pscustomobject]@{ DepartmentName = 'Picanal'; ShortName = 'Pcnl'; TemplateName = 'H-Plant-15_Pcnl' },
    [pscustomobject]@{ DepartmentName = 'Preparatory'; ShortName = 'Prep'; TemplateName = 'H-Plant-16_Prep' },
    [pscustomobject]@{ DepartmentName = 'Preparatory1'; ShortName = 'Prep1'; TemplateName = 'H-Plant-16_Prep1' },
    [pscustomobject]@{ DepartmentName = 'Preparatory2'; ShortName = 'Prep2'; TemplateName = 'H-Plant-16_Prep2' },
    [pscustomobject]@{ DepartmentName = 'Spinning'; ShortName = 'Spg'; TemplateName = 'H-Plant-16_Spg' },
    [pscustomobject]@{ DepartmentName = 'Spinning1'; ShortName = 'Spg1'; TemplateName = 'H-Plant-16_Spg1' },
    [pscustomobject]@{ DepartmentName = 'Spinning2'; ShortName = 'Spg2'; TemplateName = 'H-Plant-16_Sp2' }, # Note: Following image's template name exactly
    [pscustomobject]@{ DepartmentName = 'Spinning3'; ShortName = 'Spg3'; TemplateName = 'H-Plant-16_Spg3' },
    [pscustomobject]@{ DepartmentName = 'Winding'; ShortName = 'Wdg'; TemplateName = 'H-Plant-16_Wdg' },
    [pscustomobject]@{ DepartmentName = 'Open End'; ShortName = 'OE'; TemplateName = 'H-Plant-16_OE' },
    [pscustomobject]@{ DepartmentName = 'TFO'; ShortName = 'TFO'; TemplateName = 'H-Plant-16_TFO' },
    [pscustomobject]@{ DepartmentName = 'LinkConer'; ShortName = 'Lconer'; TemplateName = 'H-Plant-16_Lconer' },
    [pscustomobject]@{ DepartmentName = 'AutoConer'; ShortName = 'Aconer'; TemplateName = 'H-Plant-16_Aconer' },
    [pscustomobject]@{ DepartmentName = 'Weaving'; ShortName = 'Wvg'; TemplateName = 'H-Plant-16_Wvg' },
    [pscustomobject]@{ DepartmentName = 'Weaving1'; ShortName = 'Wvg1'; TemplateName = 'H-Plant-16_Wvg1' },
    [pscustomobject]@{ DepartmentName = 'Weaving2'; ShortName = 'Wvg2'; TemplateName = 'H-Plant-16_Wvg2' },
    [pscustomobject]@{ DepartmentName = 'Warping'; ShortName = 'Warp'; TemplateName = 'H-Plant-16_Warp' },
    [pscustomobject]@{ DepartmentName = 'BlowRoom'; ShortName = 'BR'; TemplateName = 'H-Plant-16_BR' },
    [pscustomobject]@{ DepartmentName = 'WeavingLoom'; ShortName = 'WvgL'; TemplateName = 'H-Plant-16_WvgL' },
    [pscustomobject]@{ DepartmentName = 'WeavingLoom1'; ShortName = 'WvgL1'; TemplateName = 'H-Plant-16_WvgL1' },
    [pscustomobject]@{ DepartmentName = 'WeavingLoom2'; ShortName = 'WvgL2'; TemplateName = 'H-Plant-16_WvgL2' },
    [pscustomobject]@{ DepartmentName = 'WeavingLoom3'; ShortName = 'WvgL3'; TemplateName = 'H-Plant-16_WvgL3' },
    [pscustomobject]@{ DepartmentName = 'Picanal'; ShortName = 'Pcnl'; TemplateName = 'H-Plant-16_Pcnl' },
    [pscustomobject]@{ DepartmentName = 'Preparatory'; ShortName = 'Prep'; TemplateName = 'H-Plant-17_Prep' },
    [pscustomobject]@{ DepartmentName = 'Preparatory1'; ShortName = 'Prep1'; TemplateName = 'H-Plant-17_Prep1' },
    [pscustomobject]@{ DepartmentName = 'Preparatory2'; ShortName = 'Prep2'; TemplateName = 'H-Plant-17_Prep2' },
    [pscustomobject]@{ DepartmentName = 'Spinning'; ShortName = 'Spg'; TemplateName = 'H-Plant-17_Spg' },
    [pscustomobject]@{ DepartmentName = 'Spinning1'; ShortName = 'Spg1'; TemplateName = 'H-Plant-17_Spg1' },
    [pscustomobject]@{ DepartmentName = 'Spinning2'; ShortName = 'Spg2'; TemplateName = 'H-Plant-17_Sp2' }, # Note: Following image's template name exactly
    [pscustomobject]@{ DepartmentName = 'Spinning3'; ShortName = 'Spg3'; TemplateName = 'H-Plant-17_Spg3' },
    [pscustomobject]@{ DepartmentName = 'Winding'; ShortName = 'Wdg'; TemplateName = 'H-Plant-17_Wdg' },
    [pscustomobject]@{ DepartmentName = 'Open End'; ShortName = 'OE'; TemplateName = 'H-Plant-17_OE' },
    [pscustomobject]@{ DepartmentName = 'TFO'; ShortName = 'TFO'; TemplateName = 'H-Plant-17_TFO' },
    [pscustomobject]@{ DepartmentName = 'LinkConer'; ShortName = 'Lconer'; TemplateName = 'H-Plant-17_Lconer' },
    [pscustomobject]@{ DepartmentName = 'AutoConer'; ShortName = 'Aconer'; TemplateName = 'H-Plant-17_Aconer' },
    [pscustomobject]@{ DepartmentName = 'Weaving'; ShortName = 'Wvg'; TemplateName = 'H-Plant-17_Wvg' },
    [pscustomobject]@{ DepartmentName = 'Weaving1'; ShortName = 'Wvg1'; TemplateName = 'H-Plant-17_Wvg1' },
    [pscustomobject]@{ DepartmentName = 'Weaving2'; ShortName = 'Wvg2'; TemplateName = 'H-Plant-17_Wvg2' },
    [pscustomobject]@{ DepartmentName = 'Warping'; ShortName = 'Warp'; TemplateName = 'H-Plant-17_Warp' },
    [pscustomobject]@{ DepartmentName = 'BlowRoom'; ShortName = 'BR'; TemplateName = 'H-Plant-17_BR' },
    [pscustomobject]@{ DepartmentName = 'WeavingLoom'; ShortName = 'WvgL'; TemplateName = 'H-Plant-17_WvgL' },
    [pscustomobject]@{ DepartmentName = 'WeavingLoom1'; ShortName = 'WvgL1'; TemplateName = 'H-Plant-17_WvgL1' },
    [pscustomobject]@{ DepartmentName = 'WeavingLoom2'; ShortName = 'WvgL2'; TemplateName = 'H-Plant-17_WvgL2' },
    [pscustomobject]@{ DepartmentName = 'WeavingLoom3'; ShortName = 'WvgL3'; TemplateName = 'H-Plant-17_WvgL3' },
    [pscustomobject]@{ DepartmentName = 'Picanal'; ShortName = 'Pcnl'; TemplateName = 'H-Plant-17_Pcnl' },
    [pscustomobject]@{ DepartmentName = 'Preparatory'; ShortName = 'Prep'; TemplateName = 'H-Plant-18_Prep' },
    [pscustomobject]@{ DepartmentName = 'Preparatory1'; ShortName = 'Prep1'; TemplateName = 'H-Plant-18_Prep1' },
    [pscustomobject]@{ DepartmentName = 'Preparatory2'; ShortName = 'Prep2'; TemplateName = 'H-Plant-18_Prep2' },
    [pscustomobject]@{ DepartmentName = 'Spinning'; ShortName = 'Spg'; TemplateName = 'H-Plant-18_Spg' },
    [pscustomobject]@{ DepartmentName = 'Spinning1'; ShortName = 'Spg1'; TemplateName = 'H-Plant-18_Spg1' },
    [pscustomobject]@{ DepartmentName = 'Spinning2'; ShortName = 'Spg2'; TemplateName = 'H-Plant-18_Sp2' }, # Note: Following image's template name exactly
    [pscustomobject]@{ DepartmentName = 'Spinning3'; ShortName = 'Spg3'; TemplateName = 'H-Plant-18_Spg3' },
    [pscustomobject]@{ DepartmentName = 'Winding'; ShortName = 'Wdg'; TemplateName = 'H-Plant-18_Wdg' },
    [pscustomobject]@{ DepartmentName = 'Open End'; ShortName = 'OE'; TemplateName = 'H-Plant-18_OE' },
    [pscustomobject]@{ DepartmentName = 'TFO'; ShortName = 'TFO'; TemplateName = 'H-Plant-18_TFO' },
    [pscustomobject]@{ DepartmentName = 'LinkConer'; ShortName = 'Lconer'; TemplateName = 'H-Plant-18_Lconer' },
    [pscustomobject]@{ DepartmentName = 'AutoConer'; ShortName = 'Aconer'; TemplateName = 'H-Plant-18_Aconer' },
    [pscustomobject]@{ DepartmentName = 'Weaving'; ShortName = 'Wvg'; TemplateName = 'H-Plant-18_Wvg' },
    [pscustomobject]@{ DepartmentName = 'Weaving1'; ShortName = 'Wvg1'; TemplateName = 'H-Plant-18_Wvg1' },
    [pscustomobject]@{ DepartmentName = 'Weaving2'; ShortName = 'Wvg2'; TemplateName = 'H-Plant-18_Wvg2' },
    [pscustomobject]@{ DepartmentName = 'Warping'; ShortName = 'Warp'; TemplateName = 'H-Plant-18_Warp' },
    [pscustomobject]@{ DepartmentName = 'BlowRoom'; ShortName = 'BR'; TemplateName = 'H-Plant-18_BR' },
    [pscustomobject]@{ DepartmentName = 'WeavingLoom'; ShortName = 'WvgL'; TemplateName = 'H-Plant-18_WvgL' },
    [pscustomobject]@{ DepartmentName = 'WeavingLoom1'; ShortName = 'WvgL1'; TemplateName = 'H-Plant-18_WvgL1' },
    [pscustomobject]@{ DepartmentName = 'WeavingLoom2'; ShortName = 'WvgL2'; TemplateName = 'H-Plant-18_WvgL2' },
    [pscustomobject]@{ DepartmentName = 'WeavingLoom3'; ShortName = 'WvgL3'; TemplateName = 'H-Plant-18_WvgL3' },
    [pscustomobject]@{ DepartmentName = 'Picanal'; ShortName = 'Pcnl'; TemplateName = 'H-Plant-18_Pcnl' },
    [pscustomobject]@{ DepartmentName = 'Preparatory'; ShortName = 'Prep'; TemplateName = 'H-Plant-19_Prep' },
    [pscustomobject]@{ DepartmentName = 'Preparatory1'; ShortName = 'Prep1'; TemplateName = 'H-Plant-19_Prep1' },
    [pscustomobject]@{ DepartmentName = 'Preparatory2'; ShortName = 'Prep2'; TemplateName = 'H-Plant-19_Prep2' },
    [pscustomobject]@{ DepartmentName = 'Spinning'; ShortName = 'Spg'; TemplateName = 'H-Plant-19_Spg' },
    [pscustomobject]@{ DepartmentName = 'Spinning1'; ShortName = 'Spg1'; TemplateName = 'H-Plant-19_Spg1' },
    [pscustomobject]@{ DepartmentName = 'Spinning2'; ShortName = 'Spg2'; TemplateName = 'H-Plant-19_Sp2' }, # Note: Following image's template name exactly
    [pscustomobject]@{ DepartmentName = 'Spinning3'; ShortName = 'Spg3'; TemplateName = 'H-Plant-19_Spg3' },
    [pscustomobject]@{ DepartmentName = 'Winding'; ShortName = 'Wdg'; TemplateName = 'H-Plant-19_Wdg' },
    [pscustomobject]@{ DepartmentName = 'Open End'; ShortName = 'OE'; TemplateName = 'H-Plant-19_OE' },
    [pscustomobject]@{ DepartmentName = 'TFO'; ShortName = 'TFO'; TemplateName = 'H-Plant-19_TFO' },
    [pscustomobject]@{ DepartmentName = 'LinkConer'; ShortName = 'Lconer'; TemplateName = 'H-Plant-19_Lconer' },
    [pscustomobject]@{ DepartmentName = 'AutoConer'; ShortName = 'Aconer'; TemplateName = 'H-Plant-19_Aconer' },
    [pscustomobject]@{ DepartmentName = 'Weaving'; ShortName = 'Wvg'; TemplateName = 'H-Plant-19_Wvg' },
    [pscustomobject]@{ DepartmentName = 'Weaving1'; ShortName = 'Wvg1'; TemplateName = 'H-Plant-19_Wvg1' },
    [pscustomobject]@{ DepartmentName = 'Weaving2'; ShortName = 'Wvg2'; TemplateName = 'H-Plant-19_Wvg2' },
    [pscustomobject]@{ DepartmentName = 'Warping'; ShortName = 'Warp'; TemplateName = 'H-Plant-19_Warp' },
    [pscustomobject]@{ DepartmentName = 'BlowRoom'; ShortName = 'BR'; TemplateName = 'H-Plant-19_BR' },
    [pscustomobject]@{ DepartmentName = 'WeavingLoom'; ShortName = 'WvgL'; TemplateName = 'H-Plant-19_WvgL' },
    [pscustomobject]@{ DepartmentName = 'WeavingLoom1'; ShortName = 'WvgL1'; TemplateName = 'H-Plant-19_WvgL1' },
    [pscustomobject]@{ DepartmentName = 'WeavingLoom2'; ShortName = 'WvgL2'; TemplateName = 'H-Plant-19_WvgL2' },
    [pscustomobject]@{ DepartmentName = 'WeavingLoom3'; ShortName = 'WvgL3'; TemplateName = 'H-Plant-19_WvgL3' },
    [pscustomobject]@{ DepartmentName = 'Picanal'; ShortName = 'Pcnl'; TemplateName = 'H-Plant-19_Pcnl' },
    [pscustomobject]@{ DepartmentName = 'Preparatory'; ShortName = 'Prep'; TemplateName = 'H-Plant-20_Prep' },
    [pscustomobject]@{ DepartmentName = 'Preparatory1'; ShortName = 'Prep1'; TemplateName = 'H-Plant-20_Prep1' },
    [pscustomobject]@{ DepartmentName = 'Preparatory2'; ShortName = 'Prep2'; TemplateName = 'H-Plant-20_Prep2' },
    [pscustomobject]@{ DepartmentName = 'Spinning'; ShortName = 'Spg'; TemplateName = 'H-Plant-20_Spg' },
    [pscustomobject]@{ DepartmentName = 'Spinning1'; ShortName = 'Spg1'; TemplateName = 'H-Plant-20_Spg1' },
    [pscustomobject]@{ DepartmentName = 'Spinning2'; ShortName = 'Spg2'; TemplateName = 'H-Plant-20_Sp2' }, # Note: Following image's template name exactly
    [pscustomobject]@{ DepartmentName = 'Spinning3'; ShortName = 'Spg3'; TemplateName = 'H-Plant-20_Spg3' },
    [pscustomobject]@{ DepartmentName = 'Winding'; ShortName = 'Wdg'; TemplateName = 'H-Plant-20_Wdg' },
    [pscustomobject]@{ DepartmentName = 'Open End'; ShortName = 'OE'; TemplateName = 'H-Plant-20_OE' },
    [pscustomobject]@{ DepartmentName = 'TFO'; ShortName = 'TFO'; TemplateName = 'H-Plant-20_TFO' },
    [pscustomobject]@{ DepartmentName = 'LinkConer'; ShortName = 'Lconer'; TemplateName = 'H-Plant-20_Lconer' },
    [pscustomobject]@{ DepartmentName = 'AutoConer'; ShortName = 'Aconer'; TemplateName = 'H-Plant-20_Aconer' },
    [pscustomobject]@{ DepartmentName = 'Weaving'; ShortName = 'Wvg'; TemplateName = 'H-Plant-20_Wvg' },
    [pscustomobject]@{ DepartmentName = 'Weaving1'; ShortName = 'Wvg1'; TemplateName = 'H-Plant-20_Wvg1' },
    [pscustomobject]@{ DepartmentName = 'Weaving2'; ShortName = 'Wvg2'; TemplateName = 'H-Plant-20_Wvg2' },
    [pscustomobject]@{ DepartmentName = 'Warping'; ShortName = 'Warp'; TemplateName = 'H-Plant-20_Warp' },
    [pscustomobject]@{ DepartmentName = 'BlowRoom'; ShortName = 'BR'; TemplateName = 'H-Plant-20_BR' },
    [pscustomobject]@{ DepartmentName = 'WeavingLoom'; ShortName = 'WvgL'; TemplateName = 'H-Plant-20_WvgL' },
    [pscustomobject]@{ DepartmentName = 'WeavingLoom1'; ShortName = 'WvgL1'; TemplateName = 'H-Plant-20_WvgL1' },
    [pscustomobject]@{ DepartmentName = 'WeavingLoom2'; ShortName = 'WvgL2'; TemplateName = 'H-Plant-20_WvgL2' },
    [pscustomobject]@{ DepartmentName = 'WeavingLoom3'; ShortName = 'WvgL3'; TemplateName = 'H-Plant-20_WvgL3' },
    [pscustomobject]@{ DepartmentName = 'Picanal'; ShortName = 'Pcnl'; TemplateName = 'H-Plant-20_Pcnl' },
    [pscustomobject]@{ DepartmentName = 'BlowRoom'; ShortName = 'BR'; TemplateName = 'WCS-1_BR' },
    [pscustomobject]@{ DepartmentName = 'Carding'; ShortName = 'Card'; TemplateName = 'WCS-1_Card' },
    [pscustomobject]@{ DepartmentName = 'Comber'; ShortName = 'Comber'; TemplateName = 'WCS-1_Comber' },
    [pscustomobject]@{ DepartmentName = 'Preparatory'; ShortName = 'Prep'; TemplateName = 'WCS-1_Prep' },
    [pscustomobject]@{ DepartmentName = 'BlowRoom'; ShortName = 'BR'; TemplateName = 'WCS-2_BR' },
    [pscustomobject]@{ DepartmentName = 'Carding'; ShortName = 'Card'; TemplateName = 'WCS-2_Card' },
    [pscustomobject]@{ DepartmentName = 'Comber'; ShortName = 'Comber'; TemplateName = 'WCS-2_Comber' },
    [pscustomobject]@{ DepartmentName = 'Preparatory'; ShortName = 'Prep'; TemplateName = 'WCS-2_Prep' },
    [pscustomobject]@{ DepartmentName = 'BlowRoom'; ShortName = 'BR'; TemplateName = 'WCS-3_BR' },
    [pscustomobject]@{ DepartmentName = 'Carding'; ShortName = 'Card'; TemplateName = 'WCS-3_Card' },
    [pscustomobject]@{ DepartmentName = 'Comber'; ShortName = 'Comber'; TemplateName = 'WCS-3_Comber' },
    [pscustomobject]@{ DepartmentName = 'Preparatory'; ShortName = 'Prep'; TemplateName = 'WCS-3_Prep' },
    [pscustomobject]@{ DepartmentName = 'BlowRoom'; ShortName = 'BR'; TemplateName = 'WCS-4_BR' },
    [pscustomobject]@{ DepartmentName = 'Carding'; ShortName = 'Card'; TemplateName = 'WCS-4_Card' },
    [pscustomobject]@{ DepartmentName = 'Comber'; ShortName = 'Comber'; TemplateName = 'WCS-4_Comber' },
    [pscustomobject]@{ DepartmentName = 'Preparatory'; ShortName = 'Prep'; TemplateName = 'WCS-4_Prep' },
    [pscustomobject]@{ DepartmentName = 'BlowRoom'; ShortName = 'BR'; TemplateName = 'WCS-5_BR' },
    [pscustomobject]@{ DepartmentName = 'Carding'; ShortName = 'Card'; TemplateName = 'WCS-5_Card' },
    [pscustomobject]@{ DepartmentName = 'Comber'; ShortName = 'Comber'; TemplateName = 'WCS-5_Comber' },
    [pscustomobject]@{ DepartmentName = 'Preparatory'; ShortName = 'Prep'; TemplateName = 'WCS-5_Prep' }
)

# --- Script Logic ---

# Check if the source file exists before starting
if (-not (Test-Path $sourceFile)) {
    Write-Error "Error: Source file '$sourceFile' not found. Please make sure it's in the same directory as the script."
    # Pause the script to allow user to read the error in case the window closes.
    Read-Host "Press Enter to exit"
    return
}

# Read the entire content of the template file into a single string for faster processing
Write-Host "Reading template file: $sourceFile"
$templateContent = Get-Content -Path $sourceFile -Raw

# Loop through each department entry defined above
foreach ($dept in $departments) {
    $newPrefix = $dept.ShortName
    $newFileName = "$($dept.TemplateName).html"
    $newDepartmentName = $dept.DepartmentName

    Write-Host "-> Generating '$newFileName' | Replacing '$originalPrefix' with '$newPrefix'..."

    # Perform the replacement for the node prefix
    $newContent = $templateContent -replace $originalPrefix, $newPrefix

    # BONUS: Also replace the department name title for a fully complete template
    # This finds `<b><u>{{ dept_name }}</u></b>` and replaces the placeholder.
    $newContent = $newContent -replace '{{ dept_name }}', $newDepartmentName

    # Save the modified content to the new file, using UTF-8 encoding for web compatibility
    try {
        Set-Content -Path $newFileName -Value $newContent -Encoding UTF8 -ErrorAction Stop
    }
    catch {
        Write-Error "Failed to write file '$newFileName'. Error: $_"
    }
}

Write-Host ""
Write-Host "Script finished. All files have been generated successfully." -ForegroundColor Green