Autoconer_RH: 62.5
Autoconer_Temp: 37.2
Autoconer_iVa_Act_RH: 62.5
Autoconer_iVa_Act_Temp: 37.2
BR_DO_Pump_Act: 0
BR_DO_Pump_Act2: 0
BR_Damper_Pid_Para_Gain: 1.2
BR_Damper_Pid_Para_IntegrationTime: 300.0
BR_Humidity_Pid_Para_Gain: 3.0
BR_Humidity_Pid_Para_IntegrationTime: 400.0
BR_Temp_Pid_Para_Gain: 1.0
BR_Temp_Pid_Para_IntegrationTime: 1.0
BR_UPSS_Pid_Para_Gain: 1.2
BR_UPSS_Pid_Para_IntegrationTime: 350.0
BR_iFl_Damper_Output_Man_B: 0
BR_iFl_Humid_Output_Man_B: 0
BR_iFl_Humid_Output_Man_B2: 0
BR_iFl_Set_DPG_RDF_Man_B: 0
BR_iFl_Set_Humidity_Man_B: 0
BR_iFl_Start_DO_B: 0
BR_iFl_Start_DO_B2: 0
BR_iMi_DO_Man: 0
BR_iMi_DO_Man2: 0
BR_iMi_Set_DPG_Man_REF: 0.0
BR_iMi_Set_RH: 55.0
BR_iMi_Set_RH_Man_Ref: 0.0
BR_iMi_Set_Temp: 34.0
BR_iMi_Set_Temp_Man_B: 0
BR_iMi_Set_Temp_Man_Ref: 0.0
BR_iMi_Set_WoT_Man_B: 0
BR_iMi_Set_WoT_Man_Ref: 0.0
BR_iTime_Start_Pump: 15
BR_iTime_Stop_Pump: 5
BR_iVa_Act_RH: 55.2
BR_iVa_Act_Temp: 33.8
BR_iVa_DPG_RDF: -592.4
BR_iVa_Damper_Output: 90.0
BR_iVa_Damper_Output_Man_Ref: 0.0
BR_iVa_Damper_Pid_Output: 90.0
BR_iVa_Humid_Output_Man_Ref: 0.0
BR_iVa_Humid_Output_Man_Ref2: 0.0
BR_iVa_Humid_Pid_Out: 10.0
BR_iVa_Max_Damper_Output: 95.0
BR_iVa_Max_Humid_Output1: 95.0
BR_iVa_Max_RAF_UPSS: 90.0
BR_iVa_Max_SAF_UPSS: 80.0
BR_iVa_Min_Damper_Output: 5.0
BR_iVa_Min_Humd_Output1: 0.0
BR_iVa_Min_Pump_Output: 80.0
BR_iVa_Min_RAF_UPSS: 80.0
BR_iVa_Min_SAF_UPSS: 70.0
BR_iVa_Pid_Output_UPSS: 75.0
BR_iVa_Pump_Start_REF: 10.0
BR_iVa_Pump_Stop_REF: 5.0
BR_iVa_Ret_Damper_Output: 5.0
BR_iVa_Set_Temp_WoT: 26.0
BR_iVa_Temp_Pid_Output: 1.0
BR_iVa_UPSS_Output_RAF: 85.0
BR_iVa_UPSS_Output_SAF: 75.0
Blowroom_RH: 55.2
Blowroom_Temp: 33.8
DI_BR_iFl_SAFan1_OFF: 0
DI_BR_iFl_SAFan1_ON: 1
DI_BR_iFl_SAFan1_TRIP: 1
DI_BR_iFl_WasherPump1_OFF: 0
DI_BR_iFl_WasherPump1_ON: 1
DI_Prep_iFl_DCF1_OFF: 0
DI_Prep_iFl_DCF1_ON: 1
DI_Prep_iFl_DCF1_TRIP: 0
DI_Prep_iFl_RDF1_OFF: 0
DI_Prep_iFl_RDF1_ON: 1
DI_Prep_iFl_RDF1_TRIP: 0
DI_Prep_iFl_RetAFan1_OFF: 0
DI_Prep_iFl_RetAFan1_ON: 1
DI_Prep_iFl_RetAFan1_TRIP: 0
DI_Prep_iFl_SAFan1_OFF: 0
DI_Prep_iFl_SAFan1_ON: 1
DI_Prep_iFl_SAFan1_TRIP: 0
DI_Prep_iFl_ScrewCompactor1_OFF: 0
DI_Prep_iFl_ScrewCompactor1_ON: 1
DI_Prep_iFl_ScrewCompactor1_TRIP: 0
DI_Prep_iFl_WasherPump1_OFF: 0
DI_Prep_iFl_WasherPump1_ON: 1
DI_Spg1_iFl_DCF1_OFF: 0
DI_Spg1_iFl_DCF1_ON: 1
DI_Spg1_iFl_DCF1_TRIP: 0
DI_Spg1_iFl_DCF2_OFF: 0
DI_Spg1_iFl_DCF2_ON: 1
DI_Spg1_iFl_DCF2_TRIP: 0
DI_Spg1_iFl_RDF1_OFF: 0
DI_Spg1_iFl_RDF1_ON: 0
DI_Spg1_iFl_RDF1_TRIP: 0
DI_Spg1_iFl_RDF2_ON: 0
DI_Spg1_iFl_RDF2_TRIP: 0
DI_Spg1_iFl_RetAFan1_OFF: 0
DI_Spg1_iFl_RetAFan1_ON: 1
DI_Spg1_iFl_RetAFan1_TRIP: 0
DI_Spg1_iFl_RetAFan2_OFF: 0
DI_Spg1_iFl_RetAFan2_ON: 1
DI_Spg1_iFl_RetAFan2_TRIP: 0
DI_Spg1_iFl_SAFan1_OFF: 0
DI_Spg1_iFl_SAFan1_ON: 1
DI_Spg1_iFl_SAFan1_TRIP: 0
DI_Spg1_iFl_SAFan2_OFF: 0
DI_Spg1_iFl_SAFan2_ON: 1
DI_Spg1_iFl_SAFan2_TRIP: 0
DI_Spg1_iFl_ScrewCompactor1_OFF: 0
DI_Spg1_iFl_ScrewCompactor1_ON: 1
DI_Spg1_iFl_ScrewCompactor1_TRIP: 0
DI_Spg1_iFl_ScrewCompactor2_OFF: 0
DI_Spg1_iFl_ScrewCompactor2_ON: 1
DI_Spg1_iFl_ScrewCompactor2_TRIP: 0
DI_Spg1_iFl_WasherPump1_OFF: 0
DI_Spg1_iFl_WasherPump1_ON: 1
DI_Spg2_iFl_DCF1_OFF: 0
DI_Spg2_iFl_DCF1_ON: 1
DI_Spg2_iFl_DCF1_TRIP: 0
DI_Spg2_iFl_RDF1_OFF: 0
DI_Spg2_iFl_RDF1_ON: 1
DI_Spg2_iFl_RDF1_TRIP: 0
DI_Spg2_iFl_RetAFan1_OFF: 0
DI_Spg2_iFl_RetAFan1_ON: 1
DI_Spg2_iFl_RetAFan1_TRIP: 0
DI_Spg2_iFl_SAFan1_OFF: 0
DI_Spg2_iFl_SAFan1_ON: 1
DI_Spg2_iFl_SAFan1_TRIP: 0
DI_Spg2_iFl_ScrewCompactor1_OFF: 0
DI_Spg2_iFl_ScrewCompactor1_ON: 1
DI_Spg2_iFl_ScrewCompactor1_TRIP: 0
DI_Spg2_iFl_WasherPump1_OFF: 0
DI_Spg2_iFl_WasherPump1_ON: 1
Prep_DO_Pump_Act: 0
Prep_DO_Pump_Act2: 0
Prep_Damper_Pid_Para_Gain: 1.2
Prep_Damper_Pid_Para_IntegrationTime: 300.0
Prep_Humidity_Pid_Para_Gain: 3.0
Prep_Humidity_Pid_Para_IntegrationTime: 400.0
Prep_Temp_Pid_Para_Gain: 1.0
Prep_Temp_Pid_Para_IntegrationTime: 1.0
Prep_UPSS_Pid_Para_Gain: 1.2
Prep_UPSS_Pid_Para_IntegrationTime: 350.0
Prep_iFl_Damper_Output_Man_B: 0
Prep_iFl_Humid_Output_Man_B: 0
Prep_iFl_Humid_Output_Man_B2: 0
Prep_iFl_Set_DPG_RDF_Man_B: 0
Prep_iFl_Set_Humidity_Man_B: 0
Prep_iFl_Start_DO_B: 0
Prep_iFl_Start_DO_B2: 0
Prep_iMi_DO_Man: 0
Prep_iMi_DO_Man2: 0
Prep_iMi_Set_DPG_Man_REF: 0.0
Prep_iMi_Set_RH: 58.0
Prep_iMi_Set_RH_Man_Ref: 0.0
Prep_iMi_Set_Temp: 34.0
Prep_iMi_Set_Temp_Man_B: 0
Prep_iMi_Set_Temp_Man_Ref: 0.0
Prep_iMi_Set_WoT_Man_B: 0
Prep_iMi_Set_WoT_Man_Ref: 0.0
Prep_iTime_Start_Pump: 15
Prep_iTime_Stop_Pump: 5
Prep_iVa_Act_RH: 58.5
Prep_iVa_Act_Temp: 34.2
Prep_iVa_DPG_RDF: -592.4
Prep_iVa_Damper_Output: 91.0
Prep_iVa_Damper_Output_Man_Ref: 0.0
Prep_iVa_Damper_Pid_Output: 91.0
Prep_iVa_Humid_Output_Man_Ref: 0.0
Prep_iVa_Humid_Output_Man_Ref2: 0.0
Prep_iVa_Humid_Pid_Out: 11.5
Prep_iVa_Max_Damper_Output: 95.0
Prep_iVa_Max_Humid_Output1: 95.0
Prep_iVa_Max_RAF_UPSS: 90.0
Prep_iVa_Max_SAF_UPSS: 80.0
Prep_iVa_Min_Damper_Output: 5.0
Prep_iVa_Min_Humd_Output1: 0.0
Prep_iVa_Min_Pump_Output: 80.0
Prep_iVa_Min_RAF_UPSS: 80.0
Prep_iVa_Min_SAF_UPSS: 70.0
Prep_iVa_Pid_Output_UPSS: 76.0
Prep_iVa_Pump_Start_REF: 10.0
Prep_iVa_Pump_Stop_REF: 5.0
Prep_iVa_Ret_Damper_Output: 5.5
Prep_iVa_Set_Temp_WoT: 26.5
Prep_iVa_Temp_Pid_Output: 1.0
Prep_iVa_UPSS_Output_RAF: 86.0
Prep_iVa_UPSS_Output_SAF: 76.0
Preparatory 1_RH: 58.5
Preparatory 1_Temp: 34.2
Spg1_DO_Pump_Act: 0
Spg1_DO_Pump_Act2: 0
Spg1_Damper_Pid_Para_Gain: 1.2
Spg1_Damper_Pid_Para_IntegrationTime: 100.0
Spg1_Humidity_Pid_Para_Gain: 3.0
Spg1_Humidity_Pid_Para_IntegrationTime: 400.0
Spg1_Temp_Pid_Para_Gain: 10.0
Spg1_Temp_Pid_Para_IntegrationTime: 1.0
Spg1_UPSS_Pid_Para_Gain: 1.2
Spg1_UPSS_Pid_Para_IntegrationTime: 350.0
Spg1_iFl_Damper_Output_Man_B: 1
Spg1_iFl_Humid_Output_Man_B: 0
Spg1_iFl_Humid_Output_Man_B2: 0
Spg1_iFl_Set_DPG_RDF_Man_B: 1
Spg1_iFl_Set_Humidity_Man_B: 1
Spg1_iFl_Start_DO_B: 0
Spg1_iFl_Start_DO_B2: 0
Spg1_iMi_DO_Man: 0
Spg1_iMi_DO_Man2: 0
Spg1_iMi_Set_DPG_Man_REF: 0.0
Spg1_iMi_Set_RH: 55.0
Spg1_iMi_Set_RH_Man_Ref: 0.0
Spg1_iMi_Set_Temp: 36.0
Spg1_iMi_Set_Temp_Man_B: 1
Spg1_iMi_Set_Temp_Man_Ref: 0.0
Spg1_iMi_Set_WoT_Man_B: 1
Spg1_iMi_Set_WoT_Man_Ref: 0.0
Spg1_iTime_Start_Pump: 15
Spg1_iTime_Stop_Pump: 5
Spg1_iVa_Act_RH: 47.5
Spg1_iVa_Act_Temp: 38.2
Spg1_iVa_DPG_RDF: -625.8
Spg1_iVa_Damper_Output: 95.0
Spg1_iVa_Damper_Output_Man_Ref: 100.0
Spg1_iVa_Damper_Pid_Output: 100.0
Spg1_iVa_Humid_Output_Man_Ref: 0.0
Spg1_iVa_Humid_Output_Man_Ref2: 0.0
Spg1_iVa_Humid_Pid_Out: 12.9
Spg1_iVa_Max_Damper_Output: 95.0
Spg1_iVa_Max_Humid_Output1: 96.0
Spg1_iVa_Max_RAF_UPSS: 96.0
Spg1_iVa_Max_SAF_UPSS: 78.0
Spg1_iVa_Min_Damper_Output: 5.0
Spg1_iVa_Min_Humd_Output1: 0.0
Spg1_iVa_Min_Pump_Output: 80.0
Spg1_iVa_Min_RAF_UPSS: 90.0
Spg1_iVa_Min_SAF_UPSS: 70.0
Spg1_iVa_Pid_Output_UPSS: 70.0
Spg1_iVa_Pump_Start_REF: 10.0
Spg1_iVa_Pump_Stop_REF: 5.0
Spg1_iVa_Ret_Damper_Output: 5.0
Spg1_iVa_Set_Temp_WoT: 26.6
Spg1_iVa_Temp_Pid_Output: 1.0
Spg1_iVa_UPSS_Output_RAF: 90.0
Spg1_iVa_UPSS_Output_SAF: 70.0
Spg2_DO_Pump_Act: 0
Spg2_DO_Pump_Act2: 0
Spg2_Damper_Pid_Para_Gain: 1.2
Spg2_Damper_Pid_Para_IntegrationTime: 300.0
Spg2_Humidity_Pid_Para_Gain: 3.0
Spg2_Humidity_Pid_Para_IntegrationTime: 400.0
Spg2_Temp_Pid_Para_Gain: 1.0
Spg2_Temp_Pid_Para_IntegrationTime: 1.0
Spg2_UPSS_Pid_Para_Gain: 1.2
Spg2_UPSS_Pid_Para_IntegrationTime: 350.0
Spg2_iFl_Damper_Output_Man_B: 0
Spg2_iFl_Humid_Output_Man_B: 0
Spg2_iFl_Humid_Output_Man_B2: 0
Spg2_iFl_Set_DPG_RDF_Man_B: 0
Spg2_iFl_Set_Humidity_Man_B: 0
Spg2_iFl_Start_DO_B: 0
Spg2_iFl_Start_DO_B2: 0
Spg2_iMi_DO_Man: 0
Spg2_iMi_DO_Man2: 0
Spg2_iMi_Set_DPG_Man_REF: 0.0
Spg2_iMi_Set_RH: 56.0
Spg2_iMi_Set_RH_Man_Ref: 0.0
Spg2_iMi_Set_Temp: 37.0
Spg2_iMi_Set_Temp_Man_B: 0
Spg2_iMi_Set_Temp_Man_Ref: 0.0
Spg2_iMi_Set_WoT_Man_B: 0
Spg2_iMi_Set_WoT_Man_Ref: 0.0
Spg2_iTime_Start_Pump: 15
Spg2_iTime_Stop_Pump: 5
Spg2_iVa_Act_RH: 56.3
Spg2_iVa_Act_Temp: 37.5
Spg2_iVa_DPG_RDF: -630.0
Spg2_iVa_Damper_Output: 92.0
Spg2_iVa_Damper_Output_Man_Ref: 0.0
Spg2_iVa_Damper_Pid_Output: 92.5
Spg2_iVa_Humid_Output_Man_Ref: 0.0
Spg2_iVa_Humid_Output_Man_Ref2: 0.0
Spg2_iVa_Humid_Pid_Out: 12.5
Spg2_iVa_Max_Damper_Output: 95.0
Spg2_iVa_Max_Humid_Output1: 95.0
Spg2_iVa_Max_RAF_UPSS: 90.0
Spg2_iVa_Max_SAF_UPSS: 80.0
Spg2_iVa_Min_Damper_Output: 5.0
Spg2_iVa_Min_Humd_Output1: 0.0
Spg2_iVa_Min_Pump_Output: 80.0
Spg2_iVa_Min_RAF_UPSS: 80.0
Spg2_iVa_Min_SAF_UPSS: 70.0
Spg2_iVa_Pid_Output_UPSS: 72.0
Spg2_iVa_Pump_Start_REF: 10.0
Spg2_iVa_Pump_Stop_REF: 5.0
Spg2_iVa_Ret_Damper_Output: 5.0
Spg2_iVa_Set_Temp_WoT: 27.0
Spg2_iVa_Temp_Pid_Output: 1.0
Spg2_iVa_UPSS_Output_RAF: 88.0
Spg2_iVa_UPSS_Output_SAF: 72.0
Spinning 1_RH: 47.5
Spinning 1_Temp: 38.2
Spinning 2_RH: 56.3
Spinning 2_Temp: 37.5
